db_yaml: "$DB_LOC/materials_db_dev.yaml" # yaml file containing DB connection settings
duplicates_file: "files/duplicates_dev.yaml" # yaml file containing duplicate mp-ids [optional]

osti:
  elink:
    endpoint: "https://www.osti.gov/elink/2416api" # E-Link API
    user: "" # user name for elink.endpoint
    password: "" # password for elink.endpoint
  explorer:
    endpoint: "https://www.osti.gov/dataexplorer/api/v1/records" # DataCite Explorer API
    user: "" # user name for explorer.endpoint
    password: "" # password for explorer.endpoint

logging:
  send_email: false
  address: "" # email address for logging error output
