name: upgrade dependencies # https://www.oddbird.net/2022/06/01/dependabot-single-pull-request/
on:
  push:
    branches: [master, update-dependencies] # temporary on criterion for testing the workflow
  workflow_dispatch: # Allow running on-demand
  schedule:
    # Runs every Monday at 8:00 UTC (4:00 Eastern)
    - cron: "0 8 * * 1"
jobs:
  upgrade:
    name: ${{ matrix.package }} (${{ matrix.os }}/py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install updated packages with uv # using uv.lock as a requirements.txt
        # this updates the lock file and then downloads/syncs the project with the updated lock file requirements
        run: |
            uv lock --upgrade
            uv sync

      - name: Detect changes # see what changed in the lock file
        id: changes
        shell: bash
        run: |
          echo "count=$(git diff-index HEAD uv.lock | wc -l | xargs)" >> $GITHUB_OUTPUT
          echo "files=$(git ls-files --exclude-standard --others uv.lock | wc -l | xargs)" >> $GITHUB_OUTPUT
    
      - name: Test Changes # see if the project, with the changes, passes the testing workflow
        id: tests
        if: steps.changes.outputs.count > 0 || steps.changes.outputs.files > 0
        env:
          elink_api_PRODUCTION_key: ${{ secrets.ELINK_PRODUCTION_API_TOKEN }}
          elink_review_api_token: ${{ secrets.ELINK_REVIEW_API_TOKEN }}
          ELINK_REVIEW_ENDPOINT: ${{ secrets.ELINK_REVIEW_ENDPOINT }}
        run: uv run pytest tests

      - name: push & merge changes # the github workflow will exit if tests fail so no need for conditions
        id: push
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add uv.lock
          git commit --allow-empty -m "update dependencies for ${{ matrix.package }} (${{ matrix.os }}/py${{ matrix.python-version }})"
          git push -f origin ${{ github.ref_name }}:auto-dependency-upgrades-${{ matrix.package }}-${{ matrix.os }}-py${{ matrix.python-version }}
          git merge origin/auto-dependency-upgrades-${{ matrix.package }}-${{ matrix.os }}-py${{ matrix.python-version }}
        # decided to just merge, assuming everything will work after the tests. no need for pull request

      # - name: commit & push changes
      #   if: steps.changes.outputs.count > 0 || steps.changes.outputs.files > 0
      #   shell: bash
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add ${{ matrix.package }}/requirements
      #     git commit --allow-empty -m "update dependencies for ${{ matrix.package }} (${{ matrix.os }}/py${{ matrix.python-version }})"
      #     git push -f origin ${{ github.ref_name }}:auto-dependency-upgrades-${{ matrix.package }}-${{ matrix.os }}-py${{ matrix.python-version }}
